"""subscription_model_change

Revision ID: f25bb674ab49
Revises: 67661f1272b9
Create Date: 2024-02-22 23:24:23.837407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f25bb674ab49'
down_revision: Union[str, None] = '67661f1272b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('ix_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
